### ISSUE TITLE
Error in the Chrome Developer Toolbar related to missing 'ember-cli-live-reload.js'

### ISSUE THREAD

**Issue by Headcult** [recurship/angular-cli-node#2]
There is an error in the Chrome Developer Toolbar related to missing 'ember-cli-live-reload.js' file while loading the HTML file.

Even I got the same error when I tried to add Express to a new Angular 2 CLI project.

Any ideas on how to resolve this?

Here is the error:
`http://localhost:4200/ember-cli-live-reload.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

**Comment by Headcult** [comment]
Any updates on this issue? Has anyone faced this issue?

**Comment by mashhoodr** [comment]
Hello @Headcult 

Apologies for the delayed response. you need to have the ng serve running as well in order to connect to the live reload.

**Comment by Headcult** [comment]
This can be closed now as the new Angular CLI versions don't have this issue. Thank you.
